# Generated by Django 5.2.8 on 2025-12-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
