# Generated by Django 5.2.8 on 2025-12-08 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shipment_return_status_alter_order_status_and_more'),
        ('store', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem'),
        ),
    ]
