# Generated by Django 5.2.8 on 2025-12-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
